### ISSUE TITLE
callback on main thread

### ISSUE THREAD

**Issue by electic** [postmates/PMKVObserver#13]
any plans to have an option to callback on the main thread?

**Comment by lilyball** [comment]
Not really. That doesn't work very well if you use `NSKeyValueObservingOptions.prior` because by the time you handle it on the main thread, the property will have been set, so you're no longer running prior to the setter. And if PMKVObserver tried to work around this by dispatching synchronously to the main queue, that would be dangerous and could lead to deadlocks (in the event that the KVO notification occurs on a thread that holds a lock the main queue is blocked on, or that has been dispatch_sync'd to from the main thread).

Or similarly, if you aren't using that option, by the time you handle the event on the main queue, the property could have been changed again to yet another value, even though your code will likely assume it hasn't changed.

And even if that's not the case, if the property is atomic and is modified from two threads at the same time, you can end up handling the callbacks out of order.

Besides, in most cases you want to handle the KVO from the thread it was fired on. And it's pretty easy to dispatch back to the main thread yourself if necessary. So I'd rather people just dispatch manually, so that way they can decide if they need to dispatch_sync (and it's safe to do so), or can dispatch_async, or perhaps do calculations on the property from the current thread before dispatching back to the main thread to update the UI, etc.

**Comment by electic** [comment]
I see that makes a lot of sense, thank you for the explanation. Will close it for now.
