### ISSUE TITLE
Use Swift 3's #keyPath instead of strings

### ISSUE THREAD

**Issue by ldiqual** [postmates/PMKVObserver#15]
The new `#keyPath` expression that landed in Swift 3 allows to designate an ObjC selector that can be enforced by the compiler: https://github.com/apple/swift-evolution/blob/master/proposals/0062-objc-keypaths.md

It would be awesome for PMKVObserver to make use of `#keyPath` instead of relying on a simple String.

**Comment by lilyball** [comment]
I'm not sure what you mean. `#keyPath` evaluates to a string literal. There's no corresponding `KeyPath` type. Clients of PMKVObserver can (and should) use `#keyPath` when setting up the observer, but there's nothing for PMKVObserver itself to do about this.

**Comment by lilyball** [comment]
I suppose I could update the examples in the README to use `#keyPath` though.

**Comment by lilyball** [comment]
README updated in 854bc1e1b0b48f0e103e6a00efb0c466a0f8abc3.

**Comment by littleowl** [comment]
Careful. I was using #keyPath (with this great lib) until upadating to Swift 3.1 broke anything that used it with a Boolean property. For instance, a custom subclass of Operation. I thought it best to use #keyPath for sending the KVO messages. (will / did). Anyways, after Swift 3.1 I would get "executing" and "finished" instead of the expected "isExecuting" and "isFinished" :(

**Comment by lilyball** [comment]
@littleowl That's because Swift 3.1 fixed a bug with `#keyPath`, but `Operation` itself is weirdly broken. The Obj-C property is named `finished`, so the `#keyPath` is `"finished"`, but `Operation` actually expects KVO notices for `"isFinished"` (and `"isExecuting"`). Completely `Operation`'s fault, and really stupid.
