### ISSUE TITLE
Observer called on .initial but not after

### ISSUE THREAD

**Issue by SeNeO** [postmates/PMKVObserver#18]
I've been using your library for some times now and it work as intended.

I tried today to add it to  a new project but I'm unable to have the block triggered after the call for .initial.
I've tried it on xcode 9, iOS11 swift 3.2 as well as Xcode 8, iOS 10 and swift 3  without success.
I'm using version 2.0.2 of PMKVObserver.
Even in an empty project with just the following code in the root view controller, the block is called only one time and display the initial value for my property.

>     var foo:String = "foo"
>     var token:KVObserver?
>     
>     override func viewDidLoad() {
>        super.viewDidLoad()
>        // Do any additional setup after loading the view, typically from a nib.
>        
>            token = KVObserver(object: self, keyPath: "foo", options:[NSKeyValueObservingOptions.initial, NSKeyValueObservingOptions.new]) { (object, change, kvob) in
>                print(object.foo)
>            }
>        
>            DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2)) { [weak self] in
>                guard let strongSelf = self  else {return}
>                strongSelf.foo = "foooooooo"
>            }
>            foo = "fuuu"
>     }
This code result only on foo being printed one time with it's intial value : "foo".
I'm pretty sure I'm missing something very obvious but cannot find what.

**Comment by lilyball** [comment]
Your `foo` property isn't KVO-compatible. In order to use KVO with properties declared in Swift, you need to mark the property as `dynamic` (alternatively, you can use `willSet`/`didSet` observers and manually invoke the `willChangeValue(forKey:)`/`didChangeValue(forKey:)` methods). This would look like `dynamic var foo: String = "foo"`.

The way automatic KVO works is, when you observe an object, the runtime will replace the IMP of your property's setter with a new one that invokes the will/didChange methods for you. For Obj-C this all just works because setting properties always goes through method dispatch. In Swift, setting properties usually doesn't go through Obj-C method dispatch. The `dynamic` keyword forces it to go through method dispatch anyway.

Note that in Swift 4 (and maybe Swift 3.2, not sure) you also need the `@objc` attribute in addition to the `dynamic` keyword.

**Comment by SeNeO** [comment]
Thanks for your answer, I understand now my error.

I thought about KVO-compatibility but though about Swfit class vs Obj-c class inheriting from `NSObject`, but even when using `NSString` instead of `String` it didn't work. Until now I must have always use your lib to listen to core-data objects where property are indeed declared as `dynamic`

I juste tried with swift 3.2 and `@objc` is not needed.
