### ISSUE TITLE
Crash when observing keypath of object that changes across multiple threads

### ISSUE THREAD

**Issue by StatusReport** [postmates/PMKVObserver#19]
The following code causes KVO to raise an exception:
```objc
#import "ViewController.h"

#import <PMKVObserver/PMKVObserver.h>

@interface ChildObject : NSObject
@end

@implementation ChildObject
@end

@interface RootObject : NSObject
@property (strong, nonatomic) ChildObject *child;
@end

@implementation RootObject
@end

@interface Observer : NSObject

- (void)start;

@property (atomic, nullable) RootObject *root;

@end

@implementation Observer

- (void)start {
  [PMKVObserver observeObject:self keyPath:@"root.child" options:0
                        block:^(id object, NSDictionary<NSKeyValueChangeKey,id> *change,
                                PMKVObserver *kvo) {}];

  dispatch_apply(100000, dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0),
                 ^(size_t i) {
                   RootObject *root = [[RootObject alloc] init];
                   root.child = [[ChildObject alloc] init];
                   self.root = root;
                 });
}

@end

@implementation ViewController

- (void)viewDidLoad {
  [super viewDidLoad];

  Observer *observer = [[Observer alloc] init];
  [observer start];
}


@end
```

I [reported this issue to Apple](https://openradar.appspot.com/radar?id=5057820135260160), but they claim that this is the expected behavior.

Given that `PMKVObserver` mission is to provide "Modern thread-safe and type-safe key-value observing for Swift and Objective-C", I assume that this is a use-case that the library should handle.

**Comment by lilyball** [comment]
Thanks for this report. Unfortunately Apple is correct and there's nothing I can do about this because it's a violation of KVO's fundamental threading assumptions.

What's going on here is that KVO requires that the calls to `-willChangeValueForKey:` and `-didChangeValueForKey:` bracket every change to the property, and that no KVO occurs in between these. Or to put it another way, you can't change the property concurrently on multiple threads because you end up with overlapping KVO changes (where the second thread calls `-willChangeValueForKey:` before the first thread has called `-didChangeValueForKey:`, or before the first thread has even changed the observable value of the property).

The flawed assumption in this code is that the `atomic` modifier to the property affects KVO, and it doesn't. KVO swizzles the property setter to wrap it in `-willChangeValueForKey:`/`-didChangeValueForKey:` but this wrapper itself is not atomic in any sense. This new wrapper looks like

```
- (void)setRoot:(RootObject *)root {
    [self willChangeValueForKey:@"root"];
    objc_setProperty_atomic(self, _cmd, root, offsetof(Observer, _root));
    [self didChangeValueForKey:@"root"];
}
```

As you can see, the atomic portion is only the actual modification of the ivar, not the bracketing KVO calls.

In order for this to work you'll need to implement the setter manually, disable automatic KVO for it, use your own lock, and invoke the `-willSetValueForKey:`/`-didSetValueForKey:` methods inside that lock. You'll also need to implement the getter to use the same lock. If you do go down this route (and I don't really suggest it) you'll probably want to use a recursive lock in case someone tries to modify the property from within an observer callback.

**Comment by lilyball** [comment]
On an unrelated note, I really need to update the README because it turns out using the `observer: self` pattern that automatically unregisters when `self` deallocates doesn't work when using a "deep" keypath. Something about how KVO handles deep keypaths means it can't find the internal observations on the intermediate path coponents by the time it tries to clean up the observation in response to `self` deallocating. You can work around this by holding onto the `PMKVObserver` and cancelling it from within `-dealloc`. I'm mentioning this here because your sample code would run into this problem if it wasn't throwing an exception earlier.

**Comment by StatusReport** [comment]
@lilyball, thanks for the elaborated clarification! I don't remember seeing such assumptions in KVO's documentation, but I may have missed it.

**Comment by lilyball** [comment]
I don't think KVO documents this, but that's not surprising, Apple's documentation is pretty light on thread safety in general.
