### ISSUE TITLE
Strange interaction with Realm ("cannot remove observer…not registered")

### ISSUE THREAD

**Issue by zacwest** [postmates/PMKVObserver#9]
For Realm Objects, the dealloc spy doesn't seem to work. I think perhaps because they're trying their own variant of removing all observers when deallocating. For example, if I add a KVObserver to a Notification object's `application` key, when the Notification deallocs I get an exception:

> Cannot remove an observer &lt;PMKVObserver …&gt; for the key path "application" from &lt;RLMAccessor_v0_Notification …&gt; because it is not registered as an observer.

I'm working around it for now by calling `.cancel()` liberally, sort of like normal KVO deregistering but at least more safe. I'm not sure if this is really a bug in PMKVObserver, but I figured I'd at least pass on my findings.

**Comment by lilyball** [comment]
After looking through Realm, I'm pretty sure this is a Realm bug, which I'll file on them. I don't see any evidence that Realm is automatically removing observers on dealloc. However, they are doing a lot of work to track observers, and I'm not entirely sure why. From reading the comment on `RLMObservationInfo` it seems it has to do with tracking multiple observers for objects backed by a single row, and I think this is simply so they can notify observers of changes whenever a row changes. But it doesn't look like they're ever actually automatically removing observers.

However, they _are_ storing the opaque observationInfo pointer (the thing that Cocoa uses to track observers) as a member variable of their `RLMObservationInfo` C++ class. And when an object deallocates, the Cocoa runtime runs the C++ destructor of an object prior to removing associated objects (and does both of those prior to freeing the allocated memory for the object). This means the `RLMObject`'s instance variable of type`std::unique_ptr<RLMObservationInfo>` is destructed before PMKVObserver's dealloc spy is removed. And since the Cooca KVO info was stored as a member variable of `RLMObservationInfo`, assuming that the destruction of the `std::unique_ptr` zeroes out the pointer (which I really don't know but seems plausible), by the time associated objects are removed Cocoa believes that all KVO has been unregistered for the object.

However, this is definitely a bug in Realm, because all they did was make an opaque pointer that Cocoa gave them no longer accessible. But that pointer probably contains some sort of dynamically allocated memory, which means that simply dropping the pointer does not actually suffice to unregister KVO. So it's very likely that the net result of this is that any time a Realm object is deallocated while it still has observers, it probably leaks memory.

**Comment by lilyball** [comment]
After poking at this for a while, I've determined that Realm does not in fact leak the observation info, because nilling out the opaque observation info as part of dealloc still triggers the exception that's fired when an object deallocates while it still has observers registered. This is because the KVO machinery actually grabs that opaque observation info pointer prior to invoking `dealloc` on the class (and uses some black magic so its copy of the pointer gets nilled out if all observers are unregistered as part of `dealloc` running). But it's still a Realm bug because it breaks the ability to unregister observers as part of associated object teardown.

**Comment by lilyball** [comment]
Filed as realm/realm-cocoa#3346. I'll leave this issue open as documentation until that Realm issue is handled.

**Comment by zacwest** [comment]
Thanks for investigating it so thoroughly!

**Comment by oit63** [comment]
I am using KVO with Realm, and It works so far, I wannar how the problem happens, is there any code?

**Comment by lilyball** [comment]
The issue was fixed 5 days ago in Realm, but they haven't had a release since then yet and I assume you're not actually using the tip of master.

The way you can reproduce this issue is to use PMKVObserver to observe a property of a Realm object, and then allow the Realm object to deallocate without removing the observer first. If the Realm object deallocates with any PMKVObservers still attached, it should trigger the "cannot remove observer" exception.

**Comment by oit63** [comment]
I do like this, for example, I make a table contains  cells which keeps many Realm related KVO 
logics,  then I delete the cell, and the associated Realm object without manually removing the PMKVObservers, and it works fine, not triggered the exception.

**Comment by lilyball** [comment]
Are you sure you aren't leaking the Realm objects? Note that in the PMKVObserver callback block, if you capture the observed object in the block you've now created a retain cycle. This is why PMKVObserver gives you the observed object as a parameter to the block, so you can get at it without capturing it.

**Comment by oit63** [comment]
ehmm, I'll check it later. As I am in China, going for work now.
